### ISSUE TITLE
Help command?

### ISSUE THREAD

**Issue by josh-degraw** [tadamczyk/DotNetWhy#50]
I'd expect typing `dotnet why --help` to output available commands & options but it just treats that as a package to check. Listing out available commands would be very helpful to know what this tool can and can't do.

**Comment by tadamczyk** [comment]
You're right, the `--help` command is needed for this application.
I have it on my to-do list and I'll try to add that command in the next version.

**Comment by tadamczyk** [comment]
Version 2.0.0 has just been released, which introduced the `--help` command.

Thank you for your input 👍🏻
